import { createClient } from '@/lib/supabase/server';
import { createAdminClient } from '@/lib/supabase/admin';
import { NextResponse } from 'next/server';
import { jsPDF } from 'jspdf';

export async function GET(
  request: Request,
  { params }: { params: Promise<{ jobId: string }> }
) {
  const { jobId } = await params;

  try {
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const admin = createAdminClient();

    const { data: job } = await admin
      .from('web_search_jobs')
      .select('*')
      .eq('id', jobId)
      .single();

    if (!job) {
      return NextResponse.json({ error: 'Job not found' }, { status: 404 });
    }

    const { data: evidence } = await admin
      .from('web_search_evidence')
      .select('*')
      .eq('job_id', jobId)
      .order('created_at');

    const { data: profile } = await admin
      .from('profiles')
      .select('email')
      .eq('id', user.id)
      .single();

    const capturedEvidence = (evidence || []).filter((e: Record<string, unknown>) => e.capture_status === 'captured');
    const searchEvidence = (evidence || []).filter((e: Record<string, unknown>) => e.capture_status === 'search_only');
    const failedEvidence = (evidence || []).filter((e: Record<string, unknown>) => e.capture_status === 'failed');

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const contentWidth = pageWidth - 2 * margin;
    let y = margin;

    const addPageIfNeeded = (requiredSpace: number) => {
      if (y + requiredSpace > doc.internal.pageSize.getHeight() - margin) {
        doc.addPage();
        y = margin;
      }
    };

    // Cover
    doc.setFontSize(24);
    doc.setTextColor(245, 158, 11);
    doc.text('AI Web Search', margin, y);
    y += 12;

    doc.setFontSize(14);
    doc.setTextColor(100, 116, 139);
    doc.text('Web Search Evidence Report', margin, y);
    y += 20;

    doc.setFontSize(11);
    doc.setTextColor(30, 41, 59);
    doc.text(`Company: ${job.company_name}`, margin, y);
    y += 7;
    if (job.country) {
      doc.text(`Country: ${job.country}`, margin, y);
      y += 7;
    }
    doc.text(`Report Type: ${job.report_type.toUpperCase()}`, margin, y);
    y += 7;
    doc.text(`Generated: ${new Date(job.completed_at || job.created_at).toLocaleString()}`, margin, y);
    y += 7;
    doc.text(`Generated by: ${profile?.email || user.id}`, margin, y);
    y += 7;

    // Evidence Score
    const coverageScore = (job.summary_json as Record<string, string>)?.coverageScore;
    const coverageStrength = (job.summary_json as Record<string, string>)?.coverageStrength;
    if (coverageScore) {
      doc.setTextColor(245, 158, 11);
      doc.text(`Evidence Score: ${coverageScore}/100 (${coverageStrength || 'N/A'})`, margin, y);
      y += 7;
    }
    y += 8;

    // Summary
    doc.setDrawColor(245, 158, 11);
    doc.line(margin, y, pageWidth - margin, y);
    y += 10;

    doc.setFontSize(13);
    doc.setTextColor(30, 41, 59);
    doc.text('Summary', margin, y);
    y += 10;

    if (job.summary_json) {
      doc.setFontSize(9);
      const summaryEntries = Object.entries(job.summary_json as Record<string, string>)
        .filter(([key]) => !['coverageScore', 'coverageStrength'].includes(key));
      for (const [key, value] of summaryEntries) {
        addPageIfNeeded(7);
        const label = key.replace(/([A-Z])/g, ' $1').replace(/^./, (s) => s.toUpperCase());
        doc.setTextColor(100, 116, 139);
        doc.text(`${label}: `, margin, y);
        doc.setTextColor(30, 41, 59);
        doc.text(String(value), margin + 60, y);
        y += 7;
      }
    }
    y += 10;

    if (job.final_comment) {
      addPageIfNeeded(20);
      doc.setFontSize(9);
      doc.setTextColor(100, 116, 139);
      const lines = doc.splitTextToSize(job.final_comment, contentWidth);
      doc.text(lines, margin, y);
      y += lines.length * 5 + 10;
    }

    // Coverage section
    addPageIfNeeded(30);
    doc.setFontSize(11);
    doc.setTextColor(30, 41, 59);
    doc.text(`Sources: ${capturedEvidence.length} captured, ${searchEvidence.length} search-only, ${failedEvidence.length} failed`, margin, y);
    y += 12;

    // Captured Evidence
    if (capturedEvidence.length > 0) {
      addPageIfNeeded(15);
      doc.setFontSize(13);
      doc.setTextColor(30, 41, 59);
      doc.text('Captured Evidence', margin, y);
      y += 10;

      for (const item of capturedEvidence) {
        addPageIfNeeded(50);
        doc.setDrawColor(30, 41, 59);
        doc.line(margin, y, pageWidth - margin, y);
        y += 8;

        doc.setFontSize(11);
        doc.setTextColor(245, 158, 11);
        doc.text(item.section_title, margin, y);
        y += 7;

        doc.setFontSize(8);
        doc.setTextColor(100, 116, 139);
        const urlText = doc.splitTextToSize(`Source: ${item.source_url}`, contentWidth);
        doc.text(urlText, margin, y);
        y += urlText.length * 4 + 2;
        if (item.confidence) {
          doc.text(`Confidence: ${item.confidence}`, margin, y);
          y += 5;
        }
        y += 3;

        if (item.ai_comment) {
          addPageIfNeeded(20);
          doc.setFontSize(9);
          doc.setTextColor(30, 41, 59);
          const commentLines = doc.splitTextToSize(item.ai_comment, contentWidth);
          doc.text(commentLines, margin, y);
          y += commentLines.length * 5 + 3;
        }

        if (item.evidence_bullets && Array.isArray(item.evidence_bullets)) {
          for (const bullet of item.evidence_bullets) {
            addPageIfNeeded(7);
            doc.setFontSize(8);
            doc.setTextColor(30, 41, 59);
            const bulletLines = doc.splitTextToSize(`• ${bullet}`, contentWidth - 5);
            doc.text(bulletLines, margin + 3, y);
            y += bulletLines.length * 4 + 2;
          }
        }

        if (item.flags && Array.isArray(item.flags) && item.flags.length > 0) {
          addPageIfNeeded(7);
          doc.setFontSize(7);
          doc.setTextColor(100, 116, 139);
          doc.text(`Flags: ${item.flags.join(', ')}`, margin, y);
          y += 5;
        }
        y += 8;
      }
    }

    // Search Evidence
    if (searchEvidence.length > 0) {
      addPageIfNeeded(15);
      doc.setFontSize(13);
      doc.setTextColor(30, 41, 59);
      doc.text('Search Evidence (SERP only)', margin, y);
      y += 10;

      for (const item of searchEvidence) {
        addPageIfNeeded(30);
        doc.setDrawColor(200, 200, 200);
        doc.line(margin, y, pageWidth - margin, y);
        y += 6;

        doc.setFontSize(10);
        doc.setTextColor(100, 116, 139);
        doc.text(item.section_title, margin, y);
        y += 6;

        doc.setFontSize(8);
        const urlText = doc.splitTextToSize(`Source: ${item.source_url}`, contentWidth);
        doc.text(urlText, margin, y);
        y += urlText.length * 4 + 2;

        if (item.ai_comment) {
          doc.setFontSize(9);
          doc.setTextColor(30, 41, 59);
          const commentLines = doc.splitTextToSize(item.ai_comment, contentWidth);
          doc.text(commentLines, margin, y);
          y += commentLines.length * 5 + 3;
        }

        if (item.evidence_bullets && Array.isArray(item.evidence_bullets)) {
          for (const bullet of item.evidence_bullets) {
            addPageIfNeeded(7);
            doc.setFontSize(8);
            doc.setTextColor(30, 41, 59);
            const bulletLines = doc.splitTextToSize(`• ${bullet}`, contentWidth - 5);
            doc.text(bulletLines, margin + 3, y);
            y += bulletLines.length * 4 + 2;
          }
        }
        y += 5;
      }
    }

    // Attempted Sources
    if (failedEvidence.length > 0) {
      addPageIfNeeded(15);
      doc.setFontSize(13);
      doc.setTextColor(100, 116, 139);
      doc.text('Attempted Sources (Failed)', margin, y);
      y += 8;

      doc.setFontSize(8);
      for (const item of failedEvidence) {
        addPageIfNeeded(12);
        doc.setTextColor(100, 116, 139);
        doc.text(`• ${item.section_title}: ${item.source_url}`, margin + 3, y);
        y += 4;
        if (item.error_message) {
          doc.setTextColor(180, 80, 80);
          doc.text(`  ${item.error_message}`, margin + 5, y);
          y += 4;
        }
        y += 2;
      }
    }

    // Disclaimer
    addPageIfNeeded(30);
    y += 10;
    doc.setDrawColor(245, 158, 11);
    doc.line(margin, y, pageWidth - margin, y);
    y += 8;
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    const disclaimer =
      'This report was generated using publicly available web sources and automated screenshot capture. It is intended as an evidence and research aid only. Final interpretation should be reviewed by a human.';
    const disclaimerLines = doc.splitTextToSize(disclaimer, contentWidth);
    doc.text(disclaimerLines, margin, y);

    // Output
    const pdfBuffer = Buffer.from(doc.output('arraybuffer'));
    const filename = `AI_Web_Search_${job.company_name.replace(/[^a-zA-Z0-9]/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`;

    return new Response(pdfBuffer, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${filename}"`,
      },
    });
  } catch (err) {
    console.error('[API] /reports/pdf error:', err);
    return NextResponse.json(
      { error: 'PDF generation failed' },
      { status: 500 }
    );
  }
}
